### ISSUE TITLE
Define `sigil_ZIG` for use in Elixir 1.15

### ISSUE THREAD

**Issue by zachallaun** [E-xyza/zigler#353]
Elixir 1.15 [will support multi-letter uppercase sigils](https://github.com/elixir-lang/elixir/pull/12448). Multi-letter sigils will be recommended for new libraries, and existing libraries like Nx [plan to switch](https://github.com/elixir-nx/nx/issues/1114).

My thought is that `~Z` should not go away so long as Zigler supports older versions of Elixir (e.g. it shouldn't be conditionally removed if you're using Elixir 1.15), but `sigil_ZIG` could be conditionally defined:

```elixir
if Version.match?(System.version(), ">= 1.15.0-dev") do
  @doc "see `sigil_Z/2`"
  defmacro sigil_ZIG({:<<>>, meta, [zig_code]}, []) do
    quoted_code(zig_code, meta, __CALLER__)
  end
end
```

**Comment by ityonemo** [comment]
haha ok cool, this will be put on 0.11

**Comment by ityonemo** [comment]
Sorry, I'm keeping sigil Z.

**Comment by zachallaun** [comment]
All good! For what it's worth, I wasn't suggesting that sigil Z be removed, but only that sigil ZIG be added as essentially an alias for those who prefer it.
