### ISSUE TITLE
livebook compilation failed

### ISSUE THREAD

**Issue by watsy0007** [E-xyza/zigler#412]
<img width="800" alt="image" src="https://github.com/E-xyza/zigler/assets/822237/10c9a19d-54f0-44d3-849d-56965134830d">

**Comment by ityonemo** [comment]
I *think* I know what is happening!

**Comment by ityonemo** [comment]
Livebook support (if possible) will drop with 0.11

**Comment by ityonemo** [comment]
sorry for the delay.

**Comment by ityonemo** [comment]
fixed here 212d255
