### ISSUE TITLE
How effective is rescheduling a NIF?

### ISSUE THREAD

**Issue by pwtail** [E-xyza/zigler#414]
I mean, when it will be possible again. I see there is some magic with passing the zig frame to the next nif invocation. How fragile is that and is there any performance penalty?

**Comment by ityonemo** [comment]
It's not possible currently due to zig punting on bringing back async, when zig async returns I'll bring it back.

There absolutely is a performance penalty and you should measure if it's acceptable before using it.  The tradeoff is more equitable latency distribution across multiple jobs.
