### ISSUE TITLE
(KeyError) key :position not found

### ISSUE THREAD

**Issue by VasiliyS** [E-xyza/zigler#415]
I've ran into the issue with the following code:

```
defmodule Ziglr do
  use Zig, otp_app: :zigler

  ~Z"""
    const std = @import("std");
    const beam = @import("beam");

    pub fn kill_os_process(env: beam.env, pid: std.os.pid_t, sig: u8) beam.term {
        std.os.kill(pid, sig) catch |err| {
          return process_err(env, err);
        };

       return beam.make(env, .ok, .{});
    }

    fn process_err(env: beam.env, err: std.os.KillError) beam.term {
          const res =
          if (err == error.PermissionDenied)
            beam.make(env, .{.@"error", .permission_denied}, .{})
           else
            beam.make(env, .{.@"error", .unexpected_error}, .{});

          return res;
    }
    """
end
```

Which results in: 

```
(KeyError) key :position not found
    (zig_parser 0.1.8) lib/zig.parser.ex:272: Zig.Parser.put_opt/3
    (zig_parser 0.1.8) lib/zig.parser/statement.ex:14: Zig.Parser.Statement.post_traverse/5
    (zig_parser 0.1.8) Zig.Parser."Statement__50"/6
    (zig_parser 0.1.8) Zig.Parser."Block__5"/6
    (zig_parser 0.1.8) Zig.Parser."TopLevelFn__29"/6
    (zig_parser 0.1.8) Zig.Parser."TopLevelDecl__20"/6
    (zig_parser 0.1.8) Zig.Parser."ContainerDeclarations__4"/6
    (zig_parser 0.1.8) Zig.Parser."ContainerDeclarations__5"/6Elixir
```

A simpler version of the above:

```
defmodule OCSPTest.OSProcess do
  use Zig, otp_app: :zigler

  ~Z"""
  const os = @import("std").os;
  const beam = @import("beam");

  pub fn kill_os_process(env: beam.env, pid: os.pid_t, sig: u8) !beam.term {

    try os.kill(pid, sig);
    return beam.make(env, .ok, .{});
  }
  """
end
```
works fine, though.  However, it gives the following warning:

`this clause cannot match because a previous clause at line 1 always matches Elixir`

I'm very new to `Zig`, maybe I'm trying to do something stupid there as I try to convert Zig errors into `{:error, reason}` tuples.  I  do think it'd be nicer compared to receiving an exception.

**Comment by ityonemo** [comment]
this is a bug in the Zigler Parser.

**Comment by ityonemo** [comment]
![Screenshot from 2023-08-28 12-46-40](https://github.com/E-xyza/zigler/assets/1219073/3a79a6b2-7a8d-4e25-9ae2-55b0598f820d)

patch coming soon as 0.10.2

**Comment by ityonemo** [comment]
btw: @VasiliyS you probably want to set your `:otp_app` to not `:zigler`.  If otp_app is zigler and your zigler dep is `runtime: false`, then it doesn't get packaged with your system if you do `mix release`.

**Comment by VasiliyS** [comment]
That was quick! Thanks a lot, @ityonemo!  

Thank you for the suggestion re. the `:otp_app`. In my case, this is going to be a part of the test suit only. I needed a sure way to shutdown a process started via a `port`. 

On a general note, I'm so happy that `zigler` exists.  There are many cases where I wish I could easily add a NIF ( handle some string/bytes manipulation, etc) to my Elixir code. Now I don't have to deal with Rust :)

**Comment by VasiliyS** [comment]
@ityonemo  - BTW, what about this warning around `defmodule` - `this clause cannot match because a previous clause at line 1 always matches Elixir` (I still have it).  Could it be that `uses` adds something conflicting?

**Comment by ityonemo** [comment]
> Could it be that uses adds something conflicting?

This is correct, I haven't figured it out yet =( but might punt till 0.11
