### ISSUE TITLE
document to use e.enif_send usage from callbacks outside of the beam environment

### ISSUE THREAD

**Issue by ityonemo** [E-xyza/zigler#426]

**Comment by rbino** [comment]
What kind of documentation were you thinking about? I have some working code that does this in TigerBeetlex so I'm happy to contribute with some examples here

**Comment by ityonemo** [comment]
I just need to make it clear how you're supposed to use e.enif_send instead of beam.send when you don't have access to env, I think.  I am refactoring how env works in zigler for 0.12

**Comment by ityonemo** [comment]
closed, since beam.send now automatically selects based on env.
